baseURL = "/"
languageCode = "en-gb"
title = "beatso"
defaultContentLanguage = "en"
isMultilingual = false
theme = "sam"
pygmentsStyle  = "monokai" # https://help.farbox.com/pygments.html
pygmentsCodefences = true


[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "face.ico"
    homepage             = "home." # What to call the home page link
    footerText           = "Beatso"

# Metadata for Open Graph and Twitter
    description          = "I'm Beatso. I make Minecraft resource packs, amongst other stuff. This is my website." # Max 160 characters show in search results
    images               = ["cover_cropped.png"]  # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Beatso"

[[params.mainMenu]]
    link = "/about"
    text = "about."

[[params.mainMenu]]
    link = "/minecraft-stuff"
    text = "minecraft stuff."

[[params.mainMenu]]
    link = "/other-stuff"
    text = "other stuff."

[[params.mainMenu]]
    link = "https://discord.gg/bNcZjFe"
    text = "discord."
	